services:
  mega-dl-webui:
    image: ghcr.io/forbish/mega-dl-webui:latest
    user: 1000:1000
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - 8080:8080
    environment:
      DOWNLOAD_DIR: /data
      # MAX_CONCURRENT: 4
      # RETRY_COUNT: 8
      # VERIFY_DOWNLOADS: true
    volumes:
      - ./downloads:/data
    tmpfs:
      - /tmp:noexec,nosuid,size=64m
    restart: unless-stopped
