services:
  mega-dl-webui:
    build: .
    user: ${PUID:-1000}:${PGID:-1000}
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      DOWNLOAD_DIR: /data
      # MAX_CONCURRENT: 4
      # RETRY_COUNT: 12
      # VERIFY_DOWNLOADS: true
    volumes:
      - ${DOWNLOAD_PATH:-./downloads}:/data
    tmpfs:
      - /tmp:noexec,nosuid,size=64m
    restart: unless-stopped
