name: Bug Report
description: Report a bug or issue
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Paste a MEGA link...
        2. Select files...
        3. Click download...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Docker image tag or commit SHA.
      placeholder: v1.0.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - linux/amd64
        - linux/arm64
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any relevant container logs (`docker logs <container>`).
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context about the problem (compose file, environment variables, etc.).
